config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root "index#index"
  resources :posts
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post.rb
class Post < ApplicationRecord
    belongs_to :user
    validates :title, uniqueness: { case_sensitive: false },
                        presence: true,
                        length: {maximum: 128}
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :trackable, :validatable
  has_many :posts
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/index_controller.rb
class IndexController < ApplicationController
  def index
    @posts = Post.order(updated_at: :desc)
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!

  def index
    @posts = Post.all
  end

  def new
    @post = current_user.posts.build
  end

  def create
    @post = current_user.posts.build(post_params)    
    if @post.save
      flash[:notice] = "Data berhasil disimpan"
      redirect_to posts_path
    else
      render "new"
    end
  end

  def edit
    @post = current_user.posts.find(params[:id])
  end

  def update
    @post = current_user.posts.find(params[:id]) 
    if @post.update(post_params)
      flash[:notice] = "Data berhasil diubah"
      redirect_to posts_path
    else
      render "edit"
    end
  end

  def show
  end

  def destroy
    @post = Post.find(params[:id])
    @post.destroy
  end

  private
  def post_params
    params.require(:post).permit(:title, :body)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/index/index.html.erb
<div class="row">     
<div class="col-md-8">
<% @posts.each do |post| %>
    <div class="card my-4">
        <div class="card-body">
            <%= content_tag :h4, post.title, class: "card-title" %>
            <%= content_tag :h6, "oleh "+post.user.email, class: "text-muted" %>
            <%= content_tag :p, post.body %>
        </div>
        <div class="card-footer">
            <%= post.created_at.strftime("%d/%m/%Y %H:%M") %>
        </div>
    </div>        
<% end %>         
</div>   
</div>   

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>My First Ruby on Rails Project</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <nav class="navbar navbar-expand-md navbar-dark bg-dark">
      <%= link_to 'MyFirst ROR', root_path, class: "navbar-brand" %>      
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse text-center justify-content-end" id="navbarNavDropdown">
        <ul class="navbar-nav">
          <% if user_signed_in? %>
            <li class="nav-item">
              <%= link_to 'Artikel', posts_path, class: "nav-link" %>
            </li>            
          <% else %>
            <li class="nav-item">
              <%= link_to 'Masuk', new_user_session_path, class: "nav-link" %>
            </li>
            <li class="nav-item">
              <%= link_to 'Daftar', new_user_registration_path, class: "nav-link" %>
            </li>
          <% end %>
        </ul>
        <% if user_signed_in? %>
          <div class="btn-group navbar-btn ml-4">
            <button class="btn btn-primary dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"><%= current_user.email %></button>
            <div class="dropdown-menu dropdown-menu-right">
              <%= link_to 'Akun', edit_user_registration_path, class: "dropdown-item" %>
              <div class="dropdown-divider"></div>
              <%= link_to 'Keluar', destroy_user_session_path, class: "dropdown-item", method: :delete %>
            </div>
          </div>
        <% end %>
      </div>
    </nav>
    <% flash.each do |name, msg| %>
      <% if name == "notice" %>
        <%= content_tag :p, msg, class: "alert alert-success" %>
      <% elsif name == "alert" %>      
        <%= content_tag :p, msg, class: "alert alert-warning" %>      
      <% end %>
    <% end %>
    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>

app/views/posts/_form.html.erb
<div class="card my-4">
    <div class="card-body">
    <%= content_tag :h1, @formTitle, class: "card-title" %>
    <%= form_with model: @post, local: true do |form| %>

    <% if @post.errors.any? %>
        <div class="alert alert-danger">        
        <ul>
            <% @post.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
            <% end %>
        </ul>
        </div>
    <% end %>

    <div class="form-group">
        <%= form.label :title, "Judul" %>
        <%= form.text_field :title, class: "form-control" %>
    </div>
    <div class="form-group">
        <%= form.label :body, "Isi" %>
        <%= form.text_area :body, class: "form-control" %>
    </div>  
    <%= form.submit "Submit", class:"btn btn-primary", data:{"disable-with": "Proses penyimpanan..."} %>    

    <% end %>
    </div>
</div>

app/views/posts/edit.html.erb
<% @formTitle = "Ubah Artikel" %>
<%= render 'form' %>

app/views/posts/index.html.erb
<h1 class="my-4">Artikel</h1>
<p><%= link_to 'Tambah', new_post_path, class: "btn btn-primary" %></p>
<div class="table-responsive">
    <table class="table table-hover">
    <thead class="thead-light">
        <tr>
        <th scope="col">#</th>
        <th scope="col">Judul</th>
        <th scope="col">Pembuat</th>
        <th scope="col">Dibuat</th>
        <th scope="col"></th>
        </tr>
    </thead>
    <tbody>
        <% @posts.each do |post| %>
        <tr>
            <th scope="row"><%= post.id %></th>
            <td><%= post.title %></td>
            <td><%= post.user.email %></td>
            <td><%= post.created_at.strftime("%d/%m/%Y %H:%M") %></td>
            <td class="nav">
                <%= link_to 'Ubah', edit_post_path(post.id), class: "nav-link btn btn-primary btn-sm mx-1" %>
                <%= link_to 'Hapus', post, class: "destroy nav-link btn btn-danger btn-sm mx-1", method: :delete, data:{confirm: "Yakin akan dihapus?", "disable-with": "Proses hapus..."}, remote: true %>
            </td>
        </tr>
        <% end %>    
    </tbody>
    </table>
</div>

app/views/posts/new.html.erb
<% @formTitle = "Tambah Artikel" %>
<%= render 'form' %>

app/views/posts/show.html.erb
<h1>Posts#show</h1>
<p>Find me in app/views/posts/show.html.erb</p>